general:
  kafka-topic: transaction-topic

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transaction-topic
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  logging:
    level:
      root: DEBUG
      org.springframework.kafka: DEBUG